from fastapi import APIRouter
from fastapi.responses import PlainTextResponse
from app.core.models import ArchitectureTopology
from datetime import datetime

router = APIRouter(prefix="/api/export", tags=["Export"])

@router.post("/markdown", response_class=PlainTextResponse)
def export_markdown_report(topo: ArchitectureTopology):
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    summary = topo.summary

    md = f"""# 🛡️ ThreatForge AI — Architecture Threat Modeling Report
**Generated:** {now}  
**Format:** {summary.get("detected_format", "Multi-Cloud / Generic")}  
**Overall Security Score:** **{topo.security_score}/100** (Grade: **{summary.get("security_grade", "N/A")}**)

---

## 1. Executive Summary
- **Total Components (Nodes):** {summary.get("total_nodes", len(topo.nodes))}
- **Interconnections (Data Flows):** {summary.get("total_edges", len(topo.edges))}
- **Identified Security Threats:** {summary.get("total_threats", len(topo.threats))}
  - 🔴 **Critical:** {summary.get("critical_threats", 0)}
  - 🟠 **High:** {summary.get("high_threats", 0)}
  - 🟡 **Medium:** {summary.get("medium_threats", 0)}
  - 🟢 **Low:** {summary.get("low_threats", 0)}
- **Exploitable Attack Paths:** {summary.get("attack_paths_count", len(topo.attack_paths))}

---

## 2. Exploitable Attack Pivots (Red Team Vectors)
"""
    if topo.attack_paths:
        for p in topo.attack_paths:
            md += f"""### ⚠️ {p.name}
- **Risk Level:** {p.risk_level.value}
- **Entry Node:** `{p.entry_node_id}`
- **Crown Jewel Target:** `{p.target_node_id}`
- **Path Steps:** `{" -> ".join(p.path_nodes)}`
- **Impact:** {p.description}

"""
    else:
        md += "*No direct multi-hop attack paths found reaching crown jewels.*\n\n"

    md += """---

## 3. Comprehensive STRIDE & MITRE ATT&CK Findings
"""
    for idx, t in enumerate(topo.threats, 1):
        md += f"""### [{t.severity.value}] {idx}. {t.title}
- **Target:** `{t.target_name}` (`{t.target_id}`)
- **STRIDE Category:** {t.stride_category.value}
- **CVSS 4.0 Score:** {t.cvss_score} / 10.0
- **MITRE ATT&CK Technique:** `{t.mitre_technique}`
- **Blast Radius:** {", ".join([f"`{b}`" for b in t.blast_radius_nodes])}
- **Description:** {t.description}
- **Remediation Strategy:** {t.remediation_advice}

```diff
{t.code_patch if t.code_patch else "# No automated patch available"}
```

---
"""

    md += """
## 4. Architectural Node Inventory
| Node ID | Type | Trust Zone | Public Ingress | Threats Detected |
|---|---|---|---|---|
"""
    for n in topo.nodes:
        md += f"| `{n.id}` | {n.type.value} | {n.trust_zone.value} | {'YES' if n.is_public else 'NO'} | {n.threat_count} |\n"

    md += "\n\n*Report automatically generated by ThreatForge AI — Zero-Trust Architecture Engine.*"
    return md
